# Generated by Django 3.1.5 on 2021-07-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mdActorCategory',
            fields=[
                ('actorCategoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('actorCategoryName', models.CharField(blank=True, default='null', max_length=50, null=True)),
            ],
        ),
    ]
