# Generated by Django 3.1.5 on 2021-07-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBS_AssociatitionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mdAssetTypes',
            fields=[
                ('assetTypeID', models.IntegerField(primary_key=True, serialize=False)),
                ('assetType', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('parentAssetType', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('effectiveDepreciation', models.CharField(blank=True, default='null', max_length=50, null=True)),
            ],
        ),
    ]
